
# Site settings
title: FEIFEI WU
name: FEIFEI WU
subtitle:  Engineer
email: wu.feifei@sz.tsinghua.edu.cn
description: >
   Engineer
baseurl: ""
url: "https://wufeifei.github.io/"
github_username:  woofei
disqus_baseurl: "https://wufeifei.github.io/"
disqus_shortname: https-wufeifei-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "FEIFEI WU"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: woofei
    url: https://github.com/woofei
    desc: Fork me on GitHub
    share: false

